# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
es:
  languageCode: es
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/es

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en
  contentDir: content/en
  title: 'Training Data Lab'
  params:
    description: 'Data and Computational Social Science Research Group'
    footer:
        copyright:
            notice: '<i class="fa-brands fa-github"></i> [GitHub repositories](https://github.com/training-datalab) &middot; <i class="fa-regular fa-calendar"></i> Last updated in December {year} <br> <i class="fa-brands fa-creative-commons"></i> 2020-{year} &middot; Training Data Lab has been supported and funded by'
  menu:
    main:
      - name: Home
        url: '#index'
        weight: 10
      - name: Team
        url: people
        weight: 20
      - name: Blog
        url: post
        weight: 30
      - name: Projects and Data
        url: project
        weight: 40
      - name: Events
        url: event
        weight: 50
      - name: Publications
        url: publication
        weight: 60
      - name: CPS-Ranking
        url: cps-ranking
        weight: 70
      - name: Working Papers
        url: tufte-working-papers
        weight: 80
